// <auto-generated />

using System;
using Data_Access_Layer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    internal class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data_Access_Layer.Models.AvailableTime", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("Available")
                    .HasColumnType("bit");

                b.Property<DateTime>("From")
                    .HasColumnType("datetime2");

                b.Property<int?>("Recurring")
                    .HasColumnType("int");

                b.Property<Guid>("ResourceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("To")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ResourceId");

                b.ToTable("AvailableTime");
            });

            modelBuilder.Entity("Data_Access_Layer.Models.Reservation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ResourceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("ResourceId");

                b.ToTable("Reservations");
            });

            modelBuilder.Entity("Data_Access_Layer.Models.ReserveTime", b =>
            {
                b.Property<Guid>("ReservationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("FromDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ToDate")
                    .HasColumnType("datetime2");

                b.HasKey("ReservationId");

                b.ToTable("ReserveTime");
            });

            modelBuilder.Entity("Data_Access_Layer.Models.Resource", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Resources");
            });

            modelBuilder.Entity("Data_Access_Layer.Models.AvailableTime", b =>
            {
                b.HasOne("Data_Access_Layer.Models.Resource", null)
                    .WithMany("TimeSlots")
                    .HasForeignKey("ResourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Data_Access_Layer.Models.Reservation", b =>
            {
                b.HasOne("Data_Access_Layer.Models.Resource", null)
                    .WithMany("Reservations")
                    .HasForeignKey("ResourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Data_Access_Layer.Models.ReserveTime", b =>
            {
                b.HasOne("Data_Access_Layer.Models.Reservation", null)
                    .WithOne("Timeslot")
                    .HasForeignKey("Data_Access_Layer.Models.ReserveTime", "ReservationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}